/* =========================================================================
   TUNK STUDIO — content.js
   Generated by admin.html on 2026-05-31T16:09:22.389Z.
   ========================================================================= */

window.TUNK_DEFAULT_CONTENT = {
  "site": {
    "title": "TUNK Studio",
    "description": "Architecture, installation & design — Istanbul.",
    "language": "EN · TR",
    "copyright": "© TUNK STUDIO · 2014—2026",
    "logoNavHeight": 28,
    "logoFooterHeight": 70
  },
  "nav": [
    {
      "id": "home",
      "label": "Studio"
    },
    {
      "id": "work",
      "label": "Work"
    },
    {
      "id": "about",
      "label": "About"
    },
    {
      "id": "press",
      "label": "Press"
    },
    {
      "id": "contact",
      "label": "Contact"
    }
  ],
  "theme": {
    "colors": {
      "ink": "#0A0A0A",
      "paper": "#FFFFFF",
      "bone": "#F4F3EF",
      "concrete": "#E8E7E2",
      "aluminium": "#B8B8B5",
      "graphite": "#5A5A57",
      "carbon": "#1C1C1B",
      "blueGlass": "#1C3FBF",
      "redPlexi": "#D4271E",
      "amber": "#C97A1A"
    },
    "fonts": {
      "sans": "'Gotham', 'Helvetica Neue', Arial, sans-serif",
      "mono": "'JetBrains Mono', ui-monospace, Menlo, monospace"
    }
  },
  "home": {
    "heroEyebrow": "STUDIO",
    "heroTitle": "Architecture,\ninstallation & design.",
    "heroIntro1": "TUNK is a studio for architecture, installation and design, based in Istanbul. The work moves between retail interiors, exhibitions and installations.",
    "heroIntro2": "Founded in 2014. Recent commissions for retail clients in Istanbul and Berlin, and exhibition design for two institutions.",
    "heroStats": [],
    "selectedWorkLabel": "Selected work",
    "selectedWorkMore": "All projects",
    "practiceLabel": "Practice",
    "practiceEyebrow": "METHOD",
    "practiceText": "The studio works between architecture and exhibition design. Each project begins with a survey of what is already there  before any new gesture is proposed.",
    "notesEyebrow": "RECENT NOTES",
    "notes": []
  },
  "work": {
    "eyebrow": "WORK",
    "title": "All projects",
    "filterLabel": "FILTER",
    "filters": [
      "All",
      "Retail",
      "Exhibition",
      "Residential",
      "Installation",
      "Adaptive Reuse"
    ],
    "gridLabel": "Grid",
    "indexLabel": "Index",
    "rangeNote": "2014—2026",
    "countNoun": "projects"
  },
  "about": {
    "eyebrow": "ABOUT",
    "heading": "Architecture, installation & design.",
    "practiceLabel": "PRACTICE",
    "p1": "TUNK was founded in Istanbul in 2014 aka MUDAHALE. The studio works between architecture, exhibition design and installation",
    "p2": "",
    "peopleLabel": "PEOPLE",
    "team": [],
    "clientsLabel": "SELECTED CLIENTS",
    "clients": []
  },
  "press": {
    "eyebrow": "PRESS",
    "title": "Press & downloads.",
    "intro": "For press enquiries, image requests and interview availability, write to tunc@tunk.studio. The materials below are provided for editorial use without further permission, with credit to the studio and named photographer.",
    "items": [],
    "downloadLabel": "Download"
  },
  "contact": {
    "eyebrow": "CONTACT",
    "title": "TUNK",
    "studioLabel": "STUDIO",
    "enquireLabel": "",
    "address": "Istanbul\nTürkiye",
    "phone": "",
    "email": "TUNC@TUNK.STUDIO",
    "pressEmail": "",
    "form": {
      "nameLabel": "Name",
      "namePlaceholder": "",
      "emailLabel": "Email",
      "emailPlaceholder": "",
      "subjectLabel": "Subject",
      "subjectPlaceholder": "",
      "budgetLabel": "Budget",
      "budgetPlaceholder": "",
      "messageLabel": "Message",
      "messagePlaceholder": "A short description of the project, site and timeline.",
      "submitLabel": "Send enquiry"
    }
  },
  "projectPage": {
    "backLabel": "← All projects",
    "prevLabel": "← Previous",
    "nextLabel": "Next →",
    "typeLabel": "Type",
    "yearLabel": "Year",
    "locationLabel": "Location",
    "areaLabel": "Area",
    "materialsLabel": "Materials",
    "photoLabel": "Photo",
    "photographer": "",
    "detailLabel": "DETAIL",
    "longShotLabel": "LONG SHOT"
  },
  "footer": {
    "tagline": "Architecture · Installation · Design",
    "location": "Istanbul",
    "studioLabel": "Studio",
    "studioLinks": [
      "Work",
      "About",
      "Press"
    ],
    "contactLabel": "Contact",
    "followLabel": "Follow",
    "instagram": "Instagram →tunkstudiotunk"
  },
  "projects": [
    {
      "id": "PL 01",
      "slug": "pneuma-pl01",
      "name": "PNEUMA",
      "kind": "Retail Interior",
      "year": 2026,
      "location": "Istanbul",
      "area": "50 m²",
      "materials": [],
      "accent": null,
      "summary": "A 50-square-metre cosmetics shop in Istanbul",
      "photos": 12,
      "tags": [
        "Retail",
        "Interior"
      ]
    },
    {
      "id": "PL 02",
      "slug": "pneuma-pl-02",
      "name": "PNEUMA MERSIN",
      "kind": "Exhibition",
      "year": 2025,
      "location": "Istanbul",
      "area": "420 m²",
      "materials": [],
      "accent": null,
      "summary": "Retail for Parfumlab",
      "photos": 18,
      "tags": []
    }
  ]
};

function TUNK_DEEP_MERGE(base, override) {
  if (override === undefined || override === null) return base;
  if (Array.isArray(base) || Array.isArray(override)) return override;
  if (typeof base !== "object" || typeof override !== "object") return override;
  const out = {};
  const keys = new Set([...Object.keys(base || {}), ...Object.keys(override || {})]);
  keys.forEach(k => { out[k] = TUNK_DEEP_MERGE(base ? base[k] : undefined, override[k]); });
  return out;
}

window.TUNK_GET_CONTENT = function () {
  const d = window.TUNK_DEFAULT_CONTENT;
  try {
    const saved = JSON.parse(localStorage.getItem("tunk_content") || "null");
    return saved ? TUNK_DEEP_MERGE(d, saved) : d;
  } catch (e) { return d; }
};
window.TUNK_SAVE_CONTENT = function (c) { localStorage.setItem("tunk_content", JSON.stringify(c)); };
window.TUNK_CLEAR_CONTENT = function () { localStorage.removeItem("tunk_content"); };

window.TUNK_APPLY_THEME = function (content) {
  const t = (content || window.TUNK_GET_CONTENT()).theme || {};
  const c = t.colors || {}; const f = t.fonts || {};
  const hex2rgba = (hex, a) => {
    const m = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex || "");
    if (!m) return "rgba(0,0,0," + a + ")";
    return `rgba(${parseInt(m[1],16)}, ${parseInt(m[2],16)}, ${parseInt(m[3],16)}, ${a})`;
  };
  const css = `:root {
    --ink: ${c.ink};
    --paper: ${c.paper};
    --bone: ${c.bone};
    --concrete: ${c.concrete};
    --aluminium: ${c.aluminium};
    --graphite: ${c.graphite};
    --carbon: ${c.carbon};
    --blue-glass: ${c.blueGlass};
    --blue-glass-tr: ${hex2rgba(c.blueGlass, 0.18)};
    --red-plexi: ${c.redPlexi};
    --red-plexi-tr: ${hex2rgba(c.redPlexi, 0.18)};
    --amber: ${c.amber};
    --amber-tr: ${hex2rgba(c.amber, 0.18)};
    --font-sans: ${f.sans};
    --font-mono: ${f.mono};
  }`;
  let tag = document.getElementById("tunk-theme");
  if (!tag) { tag = document.createElement("style"); tag.id = "tunk-theme"; document.head.appendChild(tag); }
  tag.textContent = css;
};
