/* TUNK — site content & portfolio data (plain globals for Babel scope)
   Source of truth: TUNK_PROJE_LISTESI (client project list).
   Imagery is placeholder per brand; copy written in TUNK museum-label voice.
   Only facts present in the source are stated — no fabricated materials. */
window.DATA = {
  site: {
    discipline: "ARCHITECTURE · EXHIBITION · PRODUCT · INSTALLATION",
    language: "EN · TR",
    copyright: "© TUNK STUDIO · GALATA, ISTANBUL · 2014—",
  },

  nav: [
    { id: "home",    label: "Studio"  },
    { id: "work",    label: "Work"    },
    { id: "about",   label: "About"   },
    { id: "press",   label: "Press"   },
    { id: "contact", label: "Contact" },
  ],

  home: {
    eyebrow: "STUDIO · GALATA",
    statement: "Architecture, exhibition, product & installation.",
    statementShort: "Spatial work,\nbuilt precisely.",
    intro1: "TUNK is a studio for architecture, art and design, based in Galata, Istanbul. The work moves across four disciplines — architecture, exhibition design, product design and installation.",
    intro2: "From houses on the Aegean coast to museum exhibitions at the Pera Museum, retail concepts, furniture and lighting, and light-and-sound installations made with collaborators such as NOHlab.",
    metaCols: [
      { k: "Studio", v: "2014—23 as Müdahale\n2023 — TUNK\nIstanbul, TR" },
      { k: "Work", v: "36 projects\n2014—2028" },
      { k: "Based", v: "Galata\nIstanbul, TR" },
      { k: "Exhibited", v: "Pera Museum\nAkbank Sanat" },
    ],
    selectedLabel: "Selected work",
    selectedMore: "All projects",
  },

  method: {
    eyebrow: "№ 01 — APPROACH",
    big: "Each project begins with a survey of what is already there — structure, light, the materials in use — before any new gesture is proposed.",
    steps: [
      { num: "01", t: "Survey", d: "We measure the existing condition before drawing. Structure, daylight and the materials already in the room set the terms." },
      { num: "02", t: "Reduce", d: "The work uses as few elements as possible, deployed precisely. A threshold, a partition, a single line of light." },
      { num: "03", t: "Bind colour to material", d: "Where colour appears it belongs to a real material in the project, never applied as decoration." },
      { num: "04", t: "Build", d: "Fabrication is detailed with the makers. The drawing and the built thing are held to the same tolerance." },
    ],
  },

  about: {
    eyebrow: "№ 02 — ABOUT",
    heading: "A studio for architecture, exhibition, product & installation.",
    p1: "TUNK is a studio for architecture, art and design, based in Galata, Istanbul. The studio worked as Müdahale from 2014 and took the name TUNK in 2023. The work moves across four disciplines — architecture, exhibition design, product design and installation.",
    p2: "Projects range from houses on the Aegean coast and interiors in Istanbul to museum exhibitions at the Pera Museum and Akbank Sanat, retail concepts for Parfumlab, furniture and lighting collections, and light-and-sound installations made with collaborators such as NOHlab. Recent work has been published by Arkitera, ArchDaily and Designboom.",
    disciplines: [
      { name: "Architecture", role: "Residential · interior · office · commercial · retail" },
      { name: "Exhibition Architecture", role: "Museum & gallery exhibition design" },
      { name: "Product Design", role: "Custom furniture & lighting" },
      { name: "Installation", role: "Permanent installations & art projects" },
    ],
    clients: ["Pera Museum", "Akbank Sanat", "Parfumlab", "NOHlab", "Pana Yapı", "MSGSÜ", "Arkitera", "ArchDaily", "Designboom"],
  },

  press: {
    eyebrow: "№ 03 — PRESS",
    title: "Press & coverage.",
    intro: "For press enquiries, image requests and interview availability, write to press@tunk.studio. Selected coverage below; high-resolution images are available on request, with credit to the studio and named photographer.",
    items: [
      { n: "01", name: "Oculus",            pub: "ArchDaily",    year: "2016", type: "Installation feature" },
      { n: "02", name: "Oculus",            pub: "Designboom",   year: "2016", type: "Installation feature" },
      { n: "03", name: "Postane",           pub: "Arkitera",     year: "2021", type: "Project feature" },
      { n: "04", name: "Halı Atölyesi",     pub: "Arkitera",     year: "2022", type: "Project feature" },
      { n: "05", name: "Louis Kahn",        pub: "Pera Museum",  year: "2016", type: "Exhibition design" },
      { n: "06", name: "Parajanov",         pub: "Pera Museum",  year: "2018", type: "Exhibition design" },
    ],
    downloads: [
      { n: "01", name: "Studio biography",  meta: "DOCX · 6 KB",  langs: "EN · TR" },
      { n: "02", name: "Studio logo pack",  meta: "ZIP · 2.4 MB", langs: "—" },
    ],
  },

  contact: {
    eyebrow: "№ 04 — CONTACT",
    title: "Get in touch.",
    address: "Galata\nIstanbul · Türkiye",
    phone: "",
    email: "TUNC@TUNKSTUDIO.COM",
    pressEmail: "TUNC@TUNKSTUDIO.COM",
  },

  footer: {
    tagline: "Architecture · Exhibition · Product · Installation",
    location: "Galata, Istanbul, Türkiye",
    studioLinks: ["Work", "About", "Press"],
    instagram: "Instagram →",
    newsletter: "Newsletter →",
  },

  filters: ["All", "Architecture", "Exhibition Architecture", "Product Design", "Installation"],

  /* ---------------------------------------------------------------------
     Projects — ordered by the source list's recommended top 10 first,
     then the remaining catalogue. accent stays null (material unknown =
     monochrome, per brand). tags drive the Work filter (category + scope).
     --------------------------------------------------------------------- */
  projects: [
    {
      cat: "01", slug: "postane", name: "Postane",
      category: "Architecture", kind: "Education Interior",
      year: 2021, yearLabel: "2021", location: "Istanbul", status: "Completed",
      scope: ["Furniture", "Lighting"], press: ["Arkitera"],
      tags: ["Architecture", "Product Design"],
      summary: "A cultural space in Istanbul — restaurant, bar and event venue in one building.",
      para: "The brief brought three programmes under one roof. Custom furniture and a bespoke lighting scheme were designed for the rooms, tuning each from daytime workspace to evening venue.",
    },
    {
      cat: "02", slug: "40-kapili-oda", name: "40 Kapılı Oda",
      category: "Exhibition Architecture", kind: "Immersive Exhibition",
      year: 2022, yearLabel: "2022", location: "Istanbul", status: "Completed",
      tags: ["Exhibition Architecture"],
      summary: "An immersive installation reinterpreting Ottoman architectural elements.",
      para: "The Room of Forty Doors stages a sequence of thresholds drawn from Ottoman architecture, abstracted into a single walkable volume the visitor passes through door by door.",
    },
    {
      cat: "03", slug: "louis-kahn", name: "Louis Kahn",
      category: "Exhibition Architecture", kind: "Exhibition Design",
      year: 2016, yearLabel: "2016", location: "Pera Museum, Istanbul", status: "Completed",
      press: ["Pera Museum"],
      tags: ["Exhibition Architecture"],
      summary: "Exhibition design for the Pera Museum's Louis Kahn retrospective.",
      para: "The exhibition architecture carries drawings, models and photographs of Kahn's work, holding the galleries to the same quiet, ordered measure as the buildings on the walls.",
    },
    {
      cat: "04", slug: "parajanov", name: "Parajanov",
      category: "Exhibition Architecture", kind: "Exhibition Design",
      year: 2018, yearLabel: "2018", location: "Pera Museum, Istanbul", status: "Completed",
      press: ["Pera Museum"],
      tags: ["Exhibition Architecture"],
      summary: "Exhibition design for the Pera Museum's Sergei Parajanov retrospective.",
      para: "A retrospective of the filmmaker and collagist's work. The design frames Parajanov's dense, hand-made objects without competing with them.",
    },
    {
      cat: "05", slug: "mitto", name: "Mitto",
      category: "Architecture", kind: "Commercial Interior",
      year: 2022, yearLabel: "2022", location: "Istanbul", status: "Completed",
      scope: ["Furniture"],
      tags: ["Architecture", "Product Design"],
      summary: "A commercial interior with a custom furniture collection designed for the space.",
      para: "The fit-out and its furniture were drawn together, so the loose pieces and the fixed architecture read as one decision.",
    },
    {
      cat: "06", slug: "remix", name: "Remix",
      category: "Exhibition Architecture", kind: "Exhibition",
      year: 2028, yearLabel: "2028 · forthcoming", location: "Istanbul", status: "Forthcoming",
      tags: ["Exhibition Architecture"],
      summary: "A multi-sensory exhibition architecture. Forthcoming.",
      para: "A multi-sensory exhibition in development, working across sound, light and movement through the rooms.",
    },
    {
      cat: "07", slug: "moda", name: "Moda",
      category: "Architecture", kind: "Residential Interior",
      year: 2017, yearLabel: "2017", location: "Moda, Istanbul", status: "Completed",
      tags: ["Architecture"],
      summary: "Interior for an apartment in Moda, on Istanbul's Asian shore.",
      para: "A renovation that keeps the apartment's existing proportions and reworks the plan around light and a small number of fixed moves.",
    },
    {
      cat: "08", slug: "cagan", name: "Cağan",
      category: "Architecture", kind: "Office Interior",
      year: 2020, yearLabel: "2020", location: "Istanbul", status: "Completed",
      scope: ["Furniture"],
      tags: ["Architecture", "Product Design"],
      summary: "An office interior in Istanbul with a custom furniture programme.",
      para: "Workstations, storage and meeting settings were drawn as one furniture family, organising the floor without partitions.",
    },
    {
      cat: "09", slug: "oculus", name: "Oculus",
      category: "Installation", kind: "Installation · Performance",
      year: 2016, yearLabel: "2016", location: "Istanbul", status: "Completed",
      collab: "NOHlab", press: ["ArchDaily", "Designboom"],
      tags: ["Installation"],
      summary: "An interactive light and sound performance, made in collaboration with NOHlab.",
      para: "Oculus turns a room into a single responsive instrument of light and sound. Made with NOHlab; featured by ArchDaily and Designboom.",
    },
    {
      cat: "10", slug: "galata-ormanci", name: "Galata Ormancı Apt",
      category: "Architecture", kind: "Residential Interior",
      year: 2025, yearLabel: "2025", location: "Galata, Istanbul", status: "Completed",
      tags: ["Architecture"],
      summary: "Interior for an apartment in a historic Galata block.",
      para: "A flat inside an older Galata building, reworked around its existing structure and daylight with a restrained set of interventions.",
    },

    /* ---- remaining catalogue ---- */
    {
      cat: "11", slug: "yesim-evi", name: "Submarine",
      category: "Architecture", kind: "Residential",
      year: 2020, yearLabel: "2020", location: "Göcek, Muğla", status: "Completed",
      scope: ["Furniture"],
      tags: ["Architecture", "Product Design"],
      hero: "assets/projects/yesim-hero.jpg",
      gallery: ["assets/projects/yesim-02.jpg", "assets/projects/yesim-03.jpg", "assets/projects/yesim-04.jpg"],
      photographer: "TUNK",
      summary: "A house at Gökçeovacık, near Göcek on the Aegean coast.",
      para: "A coastal house set into an olive grove above Göcek. Rendered volumes open through full-height glass to the slope and the sunset; a custom furniture collection in steel and oak was designed for its rooms.",
    },
    {
      cat: "12", slug: "gaziantep", name: "Gaziantep House",
      category: "Architecture", kind: "Residential",
      year: 2022, yearLabel: "2022", location: "Karapınar, Gaziantep", status: "Completed",
      tags: ["Architecture"],
      summary: "A residence in Karapınar, Gaziantep.",
      para: "A house completed in 2022 in the Karapınar district of Gaziantep.",
    },
    {
      cat: "13", slug: "sazli", name: "Sazlı House",
      category: "Architecture", kind: "Residential",
      year: 2023, yearLabel: "2023", location: "Sazlı, Çanakkale", status: "Completed",
      tags: ["Architecture"],
      summary: "A house in Sazlı, on the Çanakkale coast.",
      para: "A coastal residence completed in 2023 near Çanakkale.",
    },
    {
      cat: "14", slug: "oregon", name: "Oregon",
      category: "Architecture", kind: "Office Interior",
      year: 2021, yearLabel: "2021", location: "Istanbul", status: "Completed",
      scope: ["Furniture"],
      tags: ["Architecture", "Product Design"],
      summary: "An office interior with a custom furniture collection.",
      para: "Office fit-out and bespoke furniture designed together as a single system.",
    },
    {
      cat: "15", slug: "cemiyet", name: "Cemiyet",
      category: "Architecture", kind: "Commercial Interior",
      year: 2018, yearLabel: "2018", location: "Istanbul", status: "Completed",
      tags: ["Architecture"],
      summary: "A commercial interior in Istanbul.",
      para: "A commercial fit-out completed in 2018.",
    },
    {
      cat: "16", slug: "hali-atolyesi", name: "MSGSU Weaving",
      category: "Architecture", kind: "Commercial Interior",
      year: 2022, yearLabel: "2022", location: "Istanbul", status: "Completed",
      press: ["Arkitera"],
      tags: ["Architecture"],
      summary: "Reorganisation and system design for a carpet-weaving workshop.",
      para: "The MSGSÜ weaving workshop was re-planned and given a new working system — looms, storage and circulation re-set around the craft. Published by Arkitera.",
    },
    {
      cat: "17", slug: "parfumlab-pneuma", name: "Parfumlab — Pneuma",
      category: "Architecture", kind: "Retail Design",
      year: 2026, yearLabel: "2026", location: "Türkiye", status: "Completed",
      tags: ["Architecture"],
      hero: "assets/projects/pneuma-hero.jpg",
      gallery: ["assets/projects/pneuma-02.jpg", "assets/projects/pneuma-03.jpg", "assets/projects/pneuma-04.jpg"],
      album: ["assets/projects/pneuma-hero.jpg", "assets/projects/pneuma-04.jpg", "assets/projects/pneuma-05.jpg", "assets/projects/pneuma-06.jpg", "assets/projects/pneuma-02.jpg", "assets/projects/pneuma-03.jpg"],
      photographer: "TUNK",
      summary: "A Parfumlab retail concept — the Pneuma store, built as a working perfume laboratory.",
      para: "The store is laid out as a laboratory: a white pipework grid runs across ceiling and walls, blue-glass panels carry the formula displays, and a mirrored island holds the bottles. Colour belongs entirely to the cobalt glass and the lab apparatus.",
    },
    {
      cat: "18", slug: "parfumlab-mersin", name: "Parfumlab — Mersin",
      category: "Architecture", kind: "Retail Design",
      year: 2025, yearLabel: "2025", location: "Mersin", status: "Completed",
      tags: ["Architecture"],
      summary: "A Parfumlab store in Mersin.",
      para: "A Parfumlab store completed in Mersin as part of the retail programme.",
    },
    {
      cat: "19", slug: "parfumlab-hilltown", name: "Parfumlab — Hilltown",
      category: "Architecture", kind: "Retail Design",
      year: 2025, yearLabel: "2025", location: "Istanbul", status: "Completed",
      tags: ["Architecture"],
      summary: "A Parfumlab store at Hilltown.",
      para: "A Parfumlab store completed at Hilltown as part of the retail programme.",
    },
    {
      cat: "20", slug: "parfumlab-moi", name: "Parfumlab — Mall of Istanbul",
      category: "Architecture", kind: "Retail Design",
      year: 2025, yearLabel: "2025", location: "Istanbul", status: "Completed",
      tags: ["Architecture"],
      summary: "A Parfumlab store at Mall of Istanbul.",
      para: "A Parfumlab store completed at Mall of Istanbul as part of the retail programme.",
    },
    {
      cat: "21", slug: "parfumlab-cepa", name: "Parfumlab — Cepa",
      category: "Architecture", kind: "Retail Design",
      year: 2026, yearLabel: "2026", location: "Ankara", status: "Forthcoming",
      tags: ["Architecture"],
      summary: "A Parfumlab store at Cepa, Ankara.",
      para: "A forthcoming Parfumlab store at Cepa in Ankara, part of the retail programme.",
    },
    {
      cat: "22", slug: "parfumlab-atlantis", name: "Parfumlab — Atlantis",
      category: "Architecture", kind: "Retail Design",
      year: 2026, yearLabel: "2026", location: "Türkiye", status: "Forthcoming",
      tags: ["Architecture"],
      summary: "A Parfumlab store — Atlantis.",
      para: "A forthcoming Parfumlab store, part of the retail programme.",
    },
    {
      cat: "23", slug: "akbank-30", name: "30 Yıl — Akbank",
      category: "Exhibition Architecture", kind: "Exhibition Design",
      year: 2023, yearLabel: "2023", location: "Akbank Sanat, Istanbul", status: "Completed",
      tags: ["Exhibition Architecture"],
      summary: "Exhibition design for the 30th edition of Akbank's Contemporary Artists programme.",
      para: "Exhibition architecture for the 30th-anniversary edition of Akbank Sanat's Contemporary Artists exhibition.",
    },
    {
      cat: "24", slug: "sakir-eczacibasi", name: "Şakir Eczacıbaşı",
      category: "Exhibition Architecture", kind: "Exhibition Design",
      year: null, yearLabel: "—", location: "Istanbul", status: "Completed",
      tags: ["Exhibition Architecture"],
      summary: "Exhibition design for a Şakir Eczacıbaşı exhibition.",
      para: "Exhibition architecture for a show of Şakir Eczacıbaşı's work.",
    },
    {
      cat: "25", slug: "samih-rifat", name: "Samih Rıfat",
      category: "Exhibition Architecture", kind: "Exhibition Design",
      year: 2025, yearLabel: "2025", location: "Istanbul", status: "Completed",
      scope: ["Lighting"],
      tags: ["Exhibition Architecture", "Product Design"],
      summary: "Exhibition design with a custom lighting scheme.",
      para: "Exhibition architecture for a Samih Rıfat show, with lighting designed specifically for the works on display.",
    },
    {
      cat: "26", slug: "gorunmeyen-anitlar", name: "Görünmeyen Anıtlar",
      category: "Exhibition Architecture", kind: "Exhibition Design",
      year: 2025, yearLabel: "2025", location: "Istanbul", status: "Completed",
      tags: ["Exhibition Architecture"],
      summary: "Exhibition design — Invisible Monuments.",
      para: "Exhibition architecture for Görünmeyen Anıtlar (Invisible Monuments).",
    },
    {
      cat: "27", slug: "liminal", name: "Liminal",
      category: "Product Design", kind: "Lighting Design",
      year: null, yearLabel: "—", location: null, status: "Completed",
      scope: ["Lighting"],
      tags: ["Product Design"],
      summary: "A custom lighting design.",
      para: "A lighting piece developed by the studio.",
    },
    {
      cat: "28", slug: "skins", name: "Skins",
      category: "Installation", kind: "Installation",
      year: 2019, yearLabel: "2019", location: "Istanbul", status: "Completed",
      tags: ["Installation"],
      summary: "Installation design.",
      para: "An installation realised in 2019.",
    },
    {
      cat: "29", slug: "yonergeler", name: "Yönergeler",
      category: "Installation", kind: "Installation",
      year: 2019, yearLabel: "2019", location: "Istanbul", status: "Completed",
      tags: ["Installation"],
      summary: "Installation design — Instructions.",
      para: "An installation realised in 2019 in collaboration with artist Yağız Özgen.",
    },
    {
      cat: "30", slug: "paintshop", name: "Paintshop",
      category: "Installation", kind: "Installation",
      year: 2023, yearLabel: "2023", location: "Istanbul", status: "Completed",
      tags: ["Installation"],
      summary: "Installation design — Boyacı.",
      para: "An installation realised in 2023 in collaboration with artist Yağız Özgen.",
    },
    {
      cat: "31", slug: "maslak-venue", name: "Maslak Venue",
      category: "Installation", kind: "Permanent Installation",
      year: null, yearLabel: "—", location: "Maslak, Istanbul", status: "Completed",
      tags: ["Installation"],
      summary: "A permanent installation for a night club in Maslak.",
      para: "A built-in installation for a Maslak night club.",
    },
    {
      cat: "32", slug: "pana-helical", name: "Pana Yapı Helical",
      category: "Installation", kind: "Permanent Installation",
      year: null, yearLabel: "—", location: "Istanbul", status: "Completed",
      collab: "Pana Yapı",
      tags: ["Installation"],
      summary: "A permanent helical installation, with Pana Yapı.",
      para: "A permanent, built-in helical installation produced with Pana Yapı.",
    },
    {
      cat: "33", slug: "kohenler-oid", name: "Kohenler OID",
      category: "Installation", kind: "Permanent Installation",
      year: null, yearLabel: "—", location: "Istanbul", status: "Completed",
      tags: ["Installation"],
      summary: "A permanent installation.",
      para: "A built-in installation produced for Kohenler.",
    },
    {
      cat: "34", slug: "kongre-merkezi", name: "Kongre Merkezi",
      category: "Installation", kind: "Temporary Installation",
      year: null, yearLabel: "—", location: "Istanbul", status: "Event-based",
      tags: ["Installation"],
      summary: "A temporary, event-based installation for a congress centre.",
      para: "A demountable installation built for an event at a congress centre — assembled, used and struck within the run of the programme.",
    },
    {
      cat: "35", slug: "tersane-duvar", name: "Tersane Duvar",
      category: "Installation", kind: "Proposal · Unrealised",
      year: null, yearLabel: "—", location: "Istanbul", status: "Unrealised",
      tags: ["Installation"],
      summary: "An unrealised proposal — a wall for the Tersane site.",
      para: "A studio proposal developed for the Tersane site that was not realised.",
    },
    {
      cat: "36", slug: "ozdilek", name: "Özdilek",
      category: "Installation", kind: "Proposal · Unrealised",
      year: null, yearLabel: "—", location: null, status: "Unrealised",
      tags: ["Installation"],
      summary: "An unrealised proposal for Özdilek.",
      para: "A studio proposal developed for Özdilek that was not realised.",
    },
  ],
};
