/* TUNK — site content & portfolio data (plain globals for Babel scope)
   Source of truth: TUNK_PROJE_LISTESI (client project list).
   Imagery is placeholder per brand; copy written in TUNK museum-label voice.
   Only facts present in the source are stated — no fabricated materials. */
// A project is "published with photography" once it has a real gallery.
window.hasPhotos = (p) => !!(p && p.gallery && p.gallery.length);
window.DATA = {
  site: {
    discipline: "ARCHITECTURE · EXHIBITION · PRODUCT · INSTALLATION",
    language: "EN · TR",
    copyright: "© TUNK STUDIO · ISTANBUL · 2014—",
  },

  nav: [
    { id: "home",    label: "Studio"  },
    { id: "work",    label: "Work"    },
    { id: "about",   label: "About"   },
    { id: "press",   label: "Press"   },
    { id: "contact", label: "Contact" },
  ],

  home: {
    eyebrow: "STUDIO · ISTANBUL",
    statement: "Architecture, exhibition, product & installation.",
    statementShort: "Spatial work,\nbuilt precisely.",
    intro1: "TUNK is a studio for architecture, art and design, based in Galata, Istanbul. The work moves across four disciplines — architecture, exhibition design, product design and installation.",
    intro2: "From houses on the Aegean coast to museum exhibitions at the Pera Museum, retail concepts, furniture and lighting, and light-and-sound installations made with collaborators such as NOHlab.",
    metaCols: [
      { k: "Studio", v: "2014—23 as MUDAHALE\n2023 — TUNK\nIstanbul" },
      { k: "Work", v: "36 projects\n2014—2028" },
      { k: "Based", v: "Galata\nIstanbul" },
      { k: "Exhibited", v: "Pera Museum\nAkbank Sanat" },
    ],
    selectedLabel: "Selected work",
    selectedMore: "All projects",
  },

  method: {
    eyebrow: "№ 01 — APPROACH",
    big: "Each project begins with a survey of what is already there — structure, light, the materials in use — before any new gesture is proposed.",
    steps: [
      { num: "01", t: "Survey", d: "We measure the existing condition before drawing. Structure, daylight and the materials already in the room set the terms." },
      { num: "02", t: "Reduce", d: "The work uses as few elements as possible, deployed precisely. A threshold, a partition, a single line of light." },
      { num: "03", t: "Bind colour to material", d: "Where colour appears it belongs to a real material in the project, never applied as decoration." },
      { num: "04", t: "Build", d: "Fabrication is detailed with the makers. The drawing and the built thing are held to the same tolerance." },
    ],
  },

  about: {
    eyebrow: "№ 02 — ABOUT",
    heading: "A studio for architecture, exhibition, product & installation.",
    p1: "TUNK is an interdisciplinary studio for architecture, art and design, based in Istanbul. Founded by Busra Tunc in 2014 under the name MUDAHALE, the studio took the name TUNK in 2023. The work moves across four disciplines: architecture, exhibition design, product & collectible design and immersive installation.\n\nProjects range from houses on the Aegean coast and interiors across Istanbul to museum and institutional exhibitions at the Pera Museum, Istanbul Modern, Akbank Sanat and the AKM Opera House. The studio designs retail concepts for Parfumlab, develops furniture and lighting collections, and produces immersive light, sound and spatial installations. Its collectible design pieces are represented internationally by Adorno Design and have been shown at design fairs including Milan Design Week and 3 Days of Design.",
    p2: "Each project begins from its own site and brief, building a specific spatial logic rather than repeating a fixed style. Recent work has been published by ArchDaily, Designboom, Frame Magazine, Dezeen and Design Milk, among others.",
    disciplines: [
      { name: "Architecture", role: "Residential · interior · office · commercial · retail" },
      { name: "Exhibition Architecture", role: "Museum & gallery exhibition design" },
      { name: "Product Design", role: "Custom furniture & lighting" },
      { name: "Installation", role: "Permanent installations & art projects" },
    ],
    clients: ["Pera Museum", "Akbank Sanat", "Parfumlab", "NOHlab", "Pana Yapı", "MSGSÜ", "Arkitera", "ArchDaily", "Designboom"],
  },

  press: {
    eyebrow: "№ 03 — PRESS",
    title: "Press & coverage.",
    intro: "For press enquiries, image requests and interview availability, write to press@tunk.studio. Selected coverage below; high-resolution images are available on request, with credit to the studio and named photographer.",
    items: [
      { n: "01", name: "OCULUS",            pub: "ArchDaily",    year: "2016", type: "Installation feature", url: "https://www.archdaily.com/874142/nohlab-and-busra-tunc-create-immersive-installation-based-on-centuries-old-architecture" },
      { n: "02", name: "OCULUS",            pub: "Designboom",   year: "2016", type: "Installation feature", url: "https://www.designboom.com/art/nohlab-busra-tunc-oculus-sound-light-performance-has-architects-istanbul-05-23-2017/" },
      { n: "03", name: "POSTANE",           pub: "Arkitera",     year: "2021", type: "Project feature", url: "https://www.arkitera.com/proje/adil-dukkanlar-ic-mekan-ve-aydinlatma-tasarimi/" },
      { n: "04", name: "MSGSÜ WEAVING WORKSHOP", pub: "Arkitera", year: "2022", type: "Project feature", url: "https://www.arkitera.com/proje/msgsu-dokuma-atolyesi-yeniden-duzenlenmesi-ve-sistem-tasarimi/" },
      { n: "05", name: "RE/FRAMING LOUIS KAHN", pub: "Pera Museum",  year: "2016", type: "Exhibition design", url: "https://www.peramuseum.org/exhibition/re-framing-louis-kahn/217" },
      { n: "06", name: "PARAJANOV WITH SARKIS", pub: "Pera Museum",  year: "2018", type: "Exhibition design", url: "https://www.peramuseum.org/exhibition/parajanov-with-sarkis/235" },
      { n: "07", name: "LIMINAL",           pub: "Designboom",   year: "2016", type: "Product feature", url: "https://www.designboom.com/design/busra-tunc-atolye-labs-lamalight-adaptablelamp-06-19-2016/" },
      { n: "08", name: "LIMINAL",           pub: "Design Milk",  year: "2016", type: "Product feature", url: "https://design-milk.com/a-minimal-lamp-inspired-by-a-single-line/" },
    ],
    downloads: [
      { n: "01", name: "Studio biography",  meta: "DOCX · 6 KB",  langs: "EN · TR" },
      { n: "02", name: "Studio logo pack",  meta: "ZIP · 2.4 MB", langs: "—" },
    ],
  },

  contact: {
    eyebrow: "№ 04 — CONTACT",
    title: "Get in touch.",
    address: "Galata\nIstanbul",
    phone: "",
    email: "TUNC@TUNKSTUDIO.COM",
    pressEmail: "TUNC@TUNKSTUDIO.COM",
  },

  footer: {
    tagline: "Architecture · Exhibition · Product · Installation",
    location: "Istanbul",
    studioLinks: ["Work", "About", "Press"],
    instagram: "Instagram →",
    instagramUrl: "https://www.instagram.com/tunkstudiotunk/",
    newsletter: "Newsletter →",
  },

  filters: ["All", "Architecture", "Exhibition Architecture", "Product Design", "Installation"],

  /* ---------------------------------------------------------------------
     Projects — ordered by the source list's recommended top 10 first,
     then the remaining catalogue. accent stays null (material unknown =
     monochrome, per brand). tags drive the Work filter (category + scope).
     --------------------------------------------------------------------- */
  projects: [
    {
      cat: "01", slug: "postane", name: "POSTANE",
      category: "Architecture", kind: "Interior & Lighting",
      year: 2021, yearLabel: "2021", location: "Istanbul", status: "Completed",
      scope: ["Furniture", "Lighting"], press: ["Arkitera"],
      tags: ["Architecture", "Product Design"],
      hero: "assets/projects/postane/hero.jpg",
      gallery: [
        "assets/projects/postane/g/01.jpg", "assets/projects/postane/g/02.jpg", "assets/projects/postane/g/03.jpg",
        "assets/projects/postane/g/04.jpg", "assets/projects/postane/g/05.jpg", "assets/projects/postane/g/06.jpg",
        "assets/projects/postane/g/07.jpg", "assets/projects/postane/g/08.jpg", "assets/projects/postane/g/09.jpg",
        "assets/projects/postane/g/10.jpg", "assets/projects/postane/g/11.jpg", "assets/projects/postane/g/12.jpg",
        "assets/projects/postane/g/13.jpg", "assets/projects/postane/g/14.jpg", "assets/projects/postane/g/15.jpg",
        "assets/projects/postane/g/16.jpg", "assets/projects/postane/g/17.jpg", "assets/projects/postane/g/18.jpg",
        "assets/projects/postane/g/19.jpg", "assets/projects/postane/g/20.jpg", "assets/projects/postane/g/21.jpg",
        "assets/projects/postane/g/22.jpg", "assets/projects/postane/g/23.jpg", "assets/projects/postane/g/24.jpg",
        "assets/projects/postane/g/25.jpg", "assets/projects/postane/g/26.jpg", "assets/projects/postane/g/27.jpg",
        "assets/projects/postane/g/28.jpg", "assets/projects/postane/g/29.jpg"
      ],
      photographer: "Emirkan Corut",
      summary: "Interior and lighting for Postane — a social and cultural hub in the Old British Post Office in Galata, completed in 1859.",
      para: "The design was drawn from what the building revealed in restoration — the volta vaulted ceiling, the wall niches, the radial motif above the door, the gridded window frames. For the two ground-floor fair-trade shops, Postane Shop and Café, each piece was designed and fabricated alongside its craftsman: a produce stand raised from the window's cast light, a gallery light tracing the grid, a deployable publications display, a bookcase angled 10° to follow the vault, and a hand-bent sun light. The studio also carried the lighting for the whole building — facade, four floors, terrace. 73 m².",
    },
    {
      cat: "02", slug: "40-kapili-oda", name: "THE ROOM WITH FORTY DOORS",
      category: "Exhibition Architecture", kind: "Immersive Exhibition",
      year: 2022, yearLabel: "2022", location: "Istanbul", status: "Completed",
      tags: ["Exhibition Architecture"],
      summary: "An immersive installation reinterpreting Ottoman architectural elements.",
      para: "The Room of Forty Doors stages a sequence of thresholds drawn from Ottoman architecture, abstracted into a single walkable volume the visitor passes through door by door.",
    },
    {
      cat: "03", slug: "louis-kahn", name: "RE/FRAMING LOUIS KAHN",
      category: "Exhibition Architecture", kind: "Exhibition Design",
      year: 2016, yearLabel: "2016", location: "Pera Museum, Istanbul", status: "Completed",
      press: ["Pera Museum"],
      tags: ["Exhibition Architecture"],
      summary: "Exhibition design for the Pera Museum's Louis Kahn retrospective.",
      para: "The exhibition architecture carries drawings, models and photographs of Kahn's work, holding the galleries to the same quiet, ordered measure as the buildings on the walls.",
    },
    {
      cat: "04", slug: "parajanov", name: "PARAJANOV WITH SARKIS",
      category: "Exhibition Architecture", kind: "Exhibition Design",
      year: 2018, yearLabel: "2018", location: "Pera Museum, Istanbul", status: "Completed",
      press: ["Pera Museum"],
      tags: ["Exhibition Architecture"],
      summary: "Exhibition design for the Pera Museum's Sergei Parajanov retrospective.",
      para: "A retrospective of the filmmaker and collagist's work. The design frames Parajanov's dense, hand-made objects without competing with them.",
    },
    {
      cat: "05", slug: "mitto", name: "Mitto",
      category: "Architecture", kind: "Commercial Interior",
      year: 2022, yearLabel: "2022", location: "Istanbul", status: "Completed",
      scope: ["Furniture"],
      tags: ["Architecture", "Product Design"],
      summary: "A commercial interior with a custom furniture collection designed for the space.",
      para: "The fit-out and its furniture were drawn together, so the loose pieces and the fixed architecture read as one decision.",
    },
    {
      cat: "06", slug: "remix", name: "Remix",
      category: "Exhibition Architecture", kind: "Exhibition",
      year: 2019, yearLabel: "2019", location: "Istanbul", status: "Forthcoming",
      tags: ["Exhibition Architecture"],
      summary: "A multi-sensory exhibition architecture. Forthcoming.",
      para: "A multi-sensory exhibition in development, working across sound, light and movement through the rooms.",
    },
    {
      cat: "07", slug: "moda", name: "Moda",
      category: "Architecture", kind: "Residential Interior",
      year: 2017, yearLabel: "2017", location: "Moda, Istanbul", status: "Completed",
      tags: ["Architecture"],
      summary: "Interior for an apartment in Moda, on Istanbul's Asian shore.",
      para: "A renovation that keeps the apartment's existing proportions and reworks the plan around light and a small number of fixed moves.",
    },
    {
      cat: "08", slug: "cagan", name: "CAGAN",
      category: "Architecture", kind: "Office Interior",
      year: 2020, yearLabel: "2020", location: "Istanbul", status: "Completed",
      scope: ["Furniture"],
      tags: ["Architecture", "Product Design"],
      summary: "An office interior in Istanbul with a custom furniture programme.",
      para: "Workstations, storage and meeting settings were drawn as one furniture family, organising the floor without partitions.",
    },
    {
      cat: "09", slug: "oculus", name: "Oculus",
      category: "Installation", kind: "Installation · Performance",
      year: 2016, yearLabel: "2016", location: "Istanbul Imperial Arsenal, Istanbul", status: "Completed",
      collab: "NOHlab, HAS Architects", press: ["ArchDaily", "Designboom"],
      heroVideo: "193355265",
      tags: ["Installation"],
      hero: "assets/projects/oculus/g/07.jpg",
      thumb: "assets/projects/oculus/g/01.jpg",
      gallery: [
        "assets/projects/oculus/g/01.jpg", "assets/projects/oculus/g/03.jpg", "assets/projects/oculus/g/04.jpg",
        "assets/projects/oculus/g/06.jpg", "assets/projects/oculus/g/08.jpg", "assets/projects/oculus/g/09.jpg",
        "assets/projects/oculus/g/05.jpg", "assets/projects/oculus/g/02.jpg", "assets/projects/oculus/g/11.jpg",
        "assets/projects/oculus/g/12.jpg", "assets/projects/oculus/g/13.jpg", "assets/projects/oculus/g/14.jpg",
        "assets/projects/oculus/g/10.jpg", "assets/projects/oculus/g/15.jpg"
      ],
      summary: "An interactive light and sound performance, for the Third Istanbul Design Biennial.",
      photographer: "Cemal Emden",
      para: "Set in the Single-Dome Hall of the Istanbul Imperial Arsenal for the Third Istanbul Design Biennial, Oculus reinterprets the 16th-century hall's geometry as a geodesic \u201clight dome\u201d \u2014 a temporary structure of triangular screens standing inside the historic dome. Visitors step into the semicircle of interlocking panels, enclosed by shifting light, sound and animation drawn from a selection of HAS Architects' work. The top of the structure is left open, so a single ray of light still finds the room's original oculus. Old and new, real and virtual, run side by side rather than one replacing the other.",
    },
    {
      cat: "10", slug: "galata-ormanci", name: "Galata Apt",
      category: "Architecture", kind: "Residential Interior",
      year: 2025, yearLabel: "2025", location: "Galata, Istanbul", status: "Completed",
      tags: ["Architecture"],
      summary: "Interior for an apartment in a historic Galata block.",
      para: "A flat inside an older Galata building, reworked around its existing structure and daylight with a restrained set of interventions.",
    },

    /* ---- remaining catalogue ---- */
    {
      cat: "11", slug: "yesim-evi", name: "SUBMARINE",
      category: "Architecture", kind: "Residential",
      year: 2020, yearLabel: "2020", location: "Göcek, Muğla", status: "Completed",
      scope: ["Furniture"],
      tags: ["Architecture", "Product Design"],
      hero: "assets/projects/submarine/hero.jpg",
      gallery: [
        "assets/projects/submarine/g/01.jpg", "assets/projects/submarine/g/02.jpg", "assets/projects/submarine/g/03.jpg",
        "assets/projects/submarine/g/04.jpg", "assets/projects/submarine/g/05.jpg", "assets/projects/submarine/g/06.jpg",
        "assets/projects/submarine/g/07.jpg", "assets/projects/submarine/g/08.png", "assets/projects/submarine/g/09.jpg",
        "assets/projects/submarine/g/10.jpg", "assets/projects/submarine/g/11.jpg", "assets/projects/submarine/g/12.jpg",
        "assets/projects/submarine/g/13.jpg", "assets/projects/submarine/g/14.jpg", "assets/projects/submarine/g/15.jpg",
        "assets/projects/submarine/g/16.jpg", "assets/projects/submarine/g/17.jpg", "assets/projects/submarine/g/18.jpg",
        "assets/projects/submarine/g/19.jpg", "assets/projects/submarine/g/20.jpg", "assets/projects/submarine/g/21.jpg"
      ],
      photographer: "TUNK", graphics: "TUNK",
      summary: "A house set into an olive grove at Gökçeovacık, above Göcek on the Aegean coast.",
      para: "Concrete volumes step into the slope and open through full-height glass to the bay and the sunset. A circular oculus is cut through the upper floor, drawing daylight down into the stone-walled rooms below. A custom furniture collection in mild steel and oak — shelving, a hall console, a bench — was drawn for the interior and fabricated to the same line as the architecture.",
    },
    {
      cat: "12", slug: "gaziantep", name: "Gaziantep House",
      category: "Architecture", kind: "Residential",
      year: 2022, yearLabel: "2022", location: "Karapınar, Gaziantep", status: "Completed",
      tags: ["Architecture"],
      summary: "A residence in Karapınar, Gaziantep.",
      para: "A house completed in 2022 in the Karapınar district of Gaziantep.",
    },
    {
      cat: "13", slug: "sazli", name: "Sazlı House",
      category: "Architecture", kind: "Residential",
      year: 2023, yearLabel: "2023", location: "Sazlı, Çanakkale", status: "Completed",
      tags: ["Architecture"],
      summary: "A house in Sazlı, on the Çanakkale coast.",
      para: "A coastal residence completed in 2023 near Çanakkale.",
    },
    {
      cat: "14", slug: "oregon", name: "Oregon",
      category: "Architecture", kind: "Office Interior",
      year: 2021, yearLabel: "2021", location: "Istanbul", status: "Completed",
      scope: ["Furniture"],
      tags: ["Architecture", "Product Design"],
      summary: "An office interior with a custom furniture collection.",
      para: "Office fit-out and bespoke furniture designed together as a single system.",
    },
    {
      cat: "15", slug: "cemiyet", name: "Cemiyet",
      category: "Architecture", kind: "Commercial Interior",
      year: 2018, yearLabel: "2018", location: "Istanbul", status: "Completed",
      tags: ["Architecture"],
      summary: "A commercial interior in Istanbul.",
      para: "A commercial fit-out completed in 2018.",
    },
    {
      cat: "16", slug: "hali-atolyesi", name: "MSGSU Weaving",
      category: "Architecture", kind: "Education Interior",
      year: 2022, yearLabel: "2022", location: "Istanbul", status: "Completed",
      press: ["Arkitera"],
      tags: ["Architecture"],
      hero: "assets/projects/msgsu/01.jpg",
      gallery: [
        "assets/projects/msgsu/02.jpg", "assets/projects/msgsu/03.jpg",
        "assets/projects/msgsu/04.jpg", "assets/projects/msgsu/05.jpg", "assets/projects/msgsu/06.jpg",
        "assets/projects/msgsu/07.jpg", "assets/projects/msgsu/08.jpg", "assets/projects/msgsu/09.jpg",
        "assets/projects/msgsu/10.jpg", "assets/projects/msgsu/11.jpg", "assets/projects/msgsu/12.jpg",
        "assets/projects/msgsu/13.jpg", "assets/projects/msgsu/14.jpg", "assets/projects/msgsu/15.jpg"
      ],
      photographer: "Emirkan Corut",
      summary: "A new working system for the weaving workshop at Mimar Sinan Fine Arts University — looms, dye storage and circulation re-set around the craft.",
      para: "The existing studio was re-planned around how the work is actually made. A blue steel armature carries the stair, the tool screens and the open shelving; dyed yarn is sorted into a wall of stacked translucent bins, read at a glance by colour. Everything new is fabricated in mild steel and left exposed — welded on site, levelled against the original arched windows and timber ceiling. Published by Arkitera.",
    },
    {
      cat: "17", slug: "parfumlab-pneuma", name: "PNEUMA I Parfumlab",
      category: "Architecture", kind: "Retail Design",
      year: 2026, yearLabel: "2026", location: "Istanbul", status: "Completed",
      tags: ["Architecture"],
      hero: "assets/projects/pneuma-hero.jpg",
      gallery: ["assets/projects/pneuma-02.jpg", "assets/projects/pneuma-03.jpg", "assets/projects/pneuma-04.jpg"],
      album: ["assets/projects/pneuma-hero.jpg", "assets/projects/pneuma-04.jpg", "assets/projects/pneuma-05.jpg", "assets/projects/pneuma-06.jpg", "assets/projects/pneuma-02.jpg", "assets/projects/pneuma-03.jpg"],
      photographer: "Hadiye Cangökçe",
      summary: "A Parfumlab retail concept — the Pneuma store, built as a working perfume laboratory.",
      para: "The store is laid out as a laboratory: a white pipework grid runs across ceiling and walls, blue-glass panels carry the formula displays, and a mirrored island holds the bottles. Colour belongs entirely to the cobalt glass and the lab apparatus.",
    },
    {
      cat: "18", slug: "parfumlab-mersin", name: "PNEUMA I MERSIN",
      category: "Architecture", kind: "Retail Design",
      year: 2025, yearLabel: "2025", location: "Mersin", status: "Completed",
      tags: ["Architecture"],
      hero: "assets/projects/mersin/foto_02.jpg",
      thumb: "assets/projects/mersin/foto_08.jpg",
      gallery: [
        "assets/projects/mersin/graphic-plan.jpg",
        "assets/projects/mersin/graphic-elevation.jpg",
        "assets/projects/mersin/elevation.mp4",
        "assets/projects/mersin/foto_01.jpg",
        "assets/projects/mersin/foto_03.jpg",
        "assets/projects/mersin/foto_04.jpg",
        "assets/projects/mersin/foto_05.jpg",
        "assets/projects/mersin/foto_06.jpg",
        "assets/projects/mersin/foto_07.jpg",
        "assets/projects/mersin/foto_08.jpg",
        "assets/projects/mersin/foto_09.jpg",
        "assets/projects/mersin/foto_09b.jpg",
        "assets/projects/mersin/foto_10.jpg",
        "assets/projects/mersin/foto_11.jpg",
        "assets/projects/mersin/foto_12.jpg",
        "assets/projects/mersin/foto_13.jpg",
        "assets/projects/mersin/foto_14.jpg",
        "assets/projects/mersin/foto_15.jpg",
        "assets/projects/mersin/foto_16.jpg",
        "assets/projects/mersin/foto_17.jpg",
        "assets/projects/mersin/foto_19.jpg",
        "assets/projects/mersin/foto_20.jpg"
      ],
      summary: "A Parfumlab store in Mersin, built on the pneumatic display system.",
      para: "A Parfumlab store completed in Mersin as part of the retail programme. The interior extends the Pneuma language \u2014 a wall of vertical tubes carrying perfume bottles like a pneumatic system, a tiled counter and a family of display plinths \u2014 tuned to the footprint of this location.",
    },
    {
      cat: "21", slug: "parfumlab-cepa", name: "PNEUMA I KIOSK",
      category: "Architecture", kind: "Retail Design",
      year: 2025, yearLabel: "2025\u20132026", location: "Ankara, Istanbul", status: "Completed",
      tags: ["Architecture"],
      hero: "assets/projects/kiosk/01.jpg",
      heroVideoLocal: "assets/projects/kiosk/xray.mp4",
      thumb: "assets/projects/kiosk/02.jpg",
      gallery: [
        "assets/projects/kiosk/02.jpg", "assets/projects/kiosk/03.jpg",
        "assets/projects/kiosk/perspective.mp4",
        "assets/projects/kiosk/04.jpg", "assets/projects/kiosk/05.jpg",
        "assets/projects/kiosk/axon1.mp4"
      ],
      summary: "A repeatable kiosk format for Parfumlab, built in three footprints.",
      para: "A modular kiosk system for Parfumlab, repeated across Ankara and Istanbul through 2025\u20132026 at three footprints \u2014 4\u00d73 m, 4\u00d74 m and 5\u00d74 m \u2014 to fit each site. A pneumatic system, display counter and a family of display units and cubes form one kit of parts, reconfigured per location.",
    },
    {
      cat: "22", slug: "parfumlab-atlantis", name: "PNEUMA DISPLAY",
      category: "Architecture", kind: "Retail Design",
      year: 2026, yearLabel: "2026", location: "Istanbul", status: "Forthcoming",
      tags: ["Architecture"],
      summary: "A Parfumlab store — Atlantis.",
      para: "A forthcoming Parfumlab store, part of the retail programme.",
    },
    {
      cat: "23", slug: "akbank-30", name: "A SPACE OF INSIGHT",
      category: "Exhibition Architecture", kind: "Exhibition Design",
      year: 2023, yearLabel: "2023", location: "Akbank Sanat, Istanbul", status: "Completed",
      tags: ["Exhibition Architecture"],
      summary: "Exhibition design for the 30th edition of Akbank's Contemporary Artists programme.",
      para: "Exhibition architecture for the 30th-anniversary edition of Akbank Sanat's Contemporary Artists exhibition.",
    },
    {
      cat: "24", slug: "sakir-eczacibasi", name: "SELECTED MOMENTS",
      category: "Exhibition Architecture", kind: "Exhibition Design",
      year: null, yearLabel: "—", location: "Istanbul", status: "Completed",
      tags: ["Exhibition Architecture"],
      summary: "Exhibition design for a Şakir Eczacıbaşı exhibition.",
      para: "Exhibition architecture for a show of Şakir Eczacıbaşı's work.",
    },
    {
      cat: "25", slug: "samih-rifat", name: "Samih Rıfat “Much Is to Be Done”",
      category: "Exhibition Architecture", kind: "Exhibition Design",
      year: 2025, yearLabel: "2025", location: "Istanbul", status: "Completed",
      scope: ["Lighting"],
      tags: ["Exhibition Architecture", "Product Design"],
      hero: "assets/projects/samih/p/01.jpg",
      thumb: "assets/projects/samih/p/02.jpg",
      gallery: [
        "assets/projects/samih/p/02.jpg", "assets/projects/samih/p/03.jpg", "assets/projects/samih/p/04.jpg",
        "assets/projects/samih/p/05.jpg", "assets/projects/samih/p/06.jpg", "assets/projects/samih/p/07.jpg",
        "assets/projects/samih/g/09.jpg", "assets/projects/samih/g/10.jpg"
      ],
      photographer: "Hadiye Cangökçe",
      summary: "Exhibition design with a custom lighting scheme.",
      para: "Exhibition architecture for a Samih Rıfat show — blue partition walls with gold edges, each work individually lit. Lighting designed specifically for the works on display.",
    },
    {
      cat: "26", slug: "gorunmeyen-anitlar", name: "INVISIBLE MONUMENTS",
      category: "Exhibition Architecture", kind: "Exhibition Design",
      year: 2025, yearLabel: "2025", location: "Istanbul", status: "Completed",
      tags: ["Exhibition Architecture"],
      summary: "Exhibition design — Invisible Monuments.",
      para: "Exhibition architecture for Görünmeyen Anıtlar (Invisible Monuments).",
    },
    {
      cat: "27", slug: "liminal", name: "Liminal",
      category: "Product Design", kind: "Lighting Design",
      year: null, yearLabel: "—", location: null, status: "Completed",
      scope: ["Lighting"],
      tags: ["Product Design"],
      hero: "assets/projects/liminal/g/04.jpg",
      thumb: "assets/projects/liminal/g/15.jpg",
      gallery: [
        "assets/projects/liminal/g/01.jpg", "assets/projects/liminal/g/02.jpg", "assets/projects/liminal/g/03.jpg",
        "assets/projects/liminal/g/05.jpg", "assets/projects/liminal/credits.mp4",
        "assets/projects/liminal/g/06.jpg", "assets/projects/liminal/g/07.jpg", "assets/projects/liminal/g/08.jpg",
        "assets/projects/liminal/g/09.jpg", "assets/projects/liminal/g/12.jpg", "assets/projects/liminal/g/13.jpg",
        "assets/projects/liminal/g/14.jpg", "assets/projects/liminal/g/15.jpg", "assets/projects/liminal/g/16.jpg",
        "assets/projects/liminal/g/10.jpg", "assets/projects/liminal/g/11.jpg"
      ],
      summary: "A custom lighting design.",
      para: "A lighting piece developed by the studio.",
    },
    {
      cat: "28", slug: "skins", name: "Skins",
      category: "Installation", kind: "Installation",
      year: 2019, yearLabel: "2019", location: "Istanbul", status: "Completed",
      tags: ["Installation"],
      summary: "Installation design.",
      para: "An installation realised in 2019.",
    },
    {
      cat: "29", slug: "yonergeler", name: "INSTRUCTIONS",
      category: "Installation", kind: "Installation",
      year: 2019, yearLabel: "2019", location: "Istanbul", status: "Completed",
      tags: ["Installation"],
      summary: "Installation design — Instructions.",
      para: "An installation realised in 2019 in collaboration with artist Yağız Özgen.",
    },
    {
      cat: "30", slug: "paintshop", name: "The Painter",
      category: "Installation", kind: "Installation",
      year: 2023, yearLabel: "2023", location: "Istanbul", status: "Completed",
      tags: ["Installation"],
      hero: "assets/projects/painter/g/03.jpg",
      thumb: "assets/projects/painter/g/02.jpg",
      gallery: [
        "assets/projects/painter/g/11.jpg", "assets/projects/painter/g/12.jpg",
        "assets/projects/painter/store.mp4",
        "assets/projects/painter/g/05.jpg", "assets/projects/painter/g/02.jpg", "assets/projects/painter/g/06.jpg",
        "assets/projects/painter/g/07.jpg", "assets/projects/painter/g/08.jpg", "assets/projects/painter/g/09.jpg",
        "assets/projects/painter/g/10.jpg", "assets/projects/painter/g/16.jpg", "assets/projects/painter/g/01.jpg",
        "assets/projects/painter/g/13.jpg", "assets/projects/painter/g/14.jpg",
        "assets/projects/painter/g/18.jpg", "assets/projects/painter/g/19.jpg"
      ],
      photographer: "Emirkan Corut, Zeynep Fırat",
      summary: "Installation design. The painter",
      para: "An installation realised in 2023 for artist Yağız Özgen's solo exhibition the Painter.",
    },
    {
      cat: "31", slug: "maslak-venue", name: "Maslak Venue",
      category: "Installation", kind: "Permanent Installation",
      year: null, yearLabel: "—", location: "Maslak, Istanbul", status: "Completed",
      tags: ["Installation"],
      summary: "A permanent installation for a night club in Maslak.",
      para: "A built-in installation for a Maslak night club.",
    },
    {
      cat: "32", slug: "pana-helical", name: "HELICAL",
      category: "Installation", kind: "Permanent Installation",
      year: null, yearLabel: "—", location: "Istanbul", status: "Completed",
      collab: "Pana Yapı",
      tags: ["Installation"],
      summary: "A permanent helical installation, with Pana Yapı.",
      para: "A permanent, built-in helical installation produced with Pana Yapı.",
    },
    {
      cat: "33", slug: "kohenler-oid", name: "OID",
      category: "Installation", kind: "Permanent Installation",
      year: null, yearLabel: "—", location: "Istanbul", status: "Completed",
      tags: ["Installation"],
      summary: "A permanent installation.",
      para: "A built-in installation produced for Kohenler.",
    },
    {
      cat: "34", slug: "kongre-merkezi", name: "Kongre Merkezi",
      category: "Installation", kind: "Temporary Installation",
      year: null, yearLabel: "—", location: "Istanbul", status: "Event-based",
      tags: ["Installation"],
      summary: "A temporary, event-based installation for a congress centre.",
      para: "A demountable installation built for an event at a congress centre — assembled, used and struck within the run of the programme.",
    },
    {
      cat: "35", slug: "tersane-duvar", name: "TERSANE",
      category: "Installation", kind: "Proposal · Unrealised",
      year: null, yearLabel: "—", location: "Istanbul", status: "Unrealised",
      tags: ["Installation"],
      summary: "An unrealised proposal — a wall for the Tersane site.",
      para: "A studio proposal developed for the Tersane site that was not realised.",
    },
    {
      cat: "36", slug: "ozdilek", name: "OZDILEK",
      category: "Installation", kind: "Proposal · Unrealised",
      year: null, yearLabel: "—", location: null, status: "Unrealised",
      tags: ["Installation"],
      summary: "An unrealised proposal for Özdilek.",
      para: "A studio proposal developed for Özdilek that was not realised.",
    },
  ],
};
